- src/tasks/env.mk
The make file doesn't use bash but sh, which parses env vars differently. To
escape the envvar VAULT_AUTH_GITHUB_TOKEN in sh, we need to use single quotes
for the string, and a double dollar sign before the name of the envvar. This
will stop the value of the env var getting displayed in the terminal after the
user has copy/pasted it.
> Fix vault error message parsing

- src/tasks/review-app.mk
`test-review-app` target is not working for default use case
See https://financialtimes.slack.com/archives/C08PF33EC/p1544106920019000
Fix for now until we find a better way.
> Revert test-review-app being able to be overridden

- src/tasks/review-app.mk
Add `REVIEW_APP_CONFIGURE_OVERRIDES` to override the override variable for nht configure
Fixes https://github.com/Financial-Times/next/issues/272
Example of it running: https://github.com/Financial-Times/next-myft-page/pull/1919#pullrequestreview-181293687
> Allow override variable for overriding configure

- README.md
- src/tasks/deploy.mk
Since EU represents production, use this by default for canary scales 🐿 v2.11.0
Fixes https://github.com/Financial-Times/next/issues/308
> Use EU app scale by default

- src/tasks/review-app.mk
Fixes https://github.com/Financial-Times/next/issues/321
TODO:
> Destroy review app if it passes tests on the master branch 🐿 v2.11.0

- src/tasks/review-app.mk
Needed when a review app has already been created, and gets returned, as
the pipeline configuration variables aren’t sync’d. This also means that
a new review app has its variables set twice, but I think that is ok.
See https://github.com/Financial-Times/next/issues/331 🐿 v2.11.0
> Configure the review app after it is created/found

- src/setup.mk
Removed check to enforce repo ownership with an ft.yml file (moving to CODEOWNERS)
🐿 v2.12.0
> Removed check to enforce repo ownership with an ft.yml file

- Makefile
- src/tasks/install.mk
- i don't know exactly why this works
- bash `.*` includes the virtual files `.` and `..`
- filtering those out seems to make this work
- also making sure `$(dotfiles)` is defined before it's used
- which based on my understanding of make variables shouldn't be needed
> fix dotfile installation, fixes #162

- dotfiles/.eslintrc.js
close #183
Since we fixed dotfile imports in n-gage more repo started picking up this configuration. One of the property was deprecated so I had to bump ecmaVersion.
> Update eslintrc to fix deprecated option

- src/tasks/install.mk
As per the following discussion on Slack: https://financialtimes.slack.com/archives/C0ECBA4GY/p1554372261034100, which followed on from this Tweet: https://twitter.com/roelvangils/status/1113074439976075264
> Add node_modules/.metadata_never_index on install

- scripts/commands/get-config.js
Enables setting of additional env choices via project `ADDITIONAL_VAULT_ENVIRONMENTS` environment variable.
In `next-myft-email` we have a need to be able to deploy to a `sandbox` environment, we also will potentially in the future desire different environment variables for a `staging` environment.
This enables this to be configurable on a project specific basis.
🐿 v2.12.3
> enable setting of additional env choices for get-config

- dotfiles/.eslintrc.js
Repos using n-gage throw linting errors for these, but the eslint.rc file was not configured to show them visibly as errors, meaning they were difficult to fix.
I've spoken with @quarterto about how this overlaps with the settings in the Editor Config file. The issue is that there doesn't seem to be a way to show red squiggly line errors for Editor Config, meaning it's difficult to fix those errors. They are looking into a future fix for this, but in the meantime have said this is a good step to take for the eslint.rc file.
> Add errors for trailing whitespace and bad indents

- dotfiles/.eslintrc.js
In a recent eslint update it seems they have defaulted the `SwichCase` rule to `0`. This means the switch statements were being auto corrected to look different from before.
For example -
```js
switch (thing) {
case 1:
...
case 2:
...
}
```
Was being formatted to be -
```js
switch (thing) {
case 1:
...
case 2:
...
}
```
> Update the SwitchCase indent rule

- src/tasks/review-app.mk
Preview apps support https.
Conversion team would like to start using the preview apps to run end2end tests.
TEST_URL exposes the app url but on http.
As all of FT is behind ssl and the review app do support ssl, it seems logical to use https.
> use https for TEST_URL

- src/tasks/deploy.mk
A simple curl request which fires off at the end of the deploy step.
Currently would send a release log to `#ft-changes`, though if we wanted to add a slack channel for this we could do that too. The release log would be useful for audit/logging purposes.
Added the api request to the end of the `deploy` command. This would not affect deployment of an app if it failed.
Need to decide whether this lives in the `deploy` job. Would prefer for this to be a separate make command, however we would then need to change a lot of repos to add this in 🙈.
> Add change api to n-gage

- src/tasks/deploy.mk
`CIRCLE_PROJECT_REPONAME` should provide a name closer to the desired `systemcode` field we want.
https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
> Use circle repo name instead of vault

- src/tasks/review-app.mk
otherwise, it prints `rm: cannot remove '.review-app': No such file or directory`, which looks like an error when you're scanning CI logs but it isn't one, which is misleading when the build breaks because it's never because of that but it looks like it's an error and it's the first thing you see
closes #187 if done with financial-times/n-heroku-tools#577
> make rm not error instead of suppressing its error

- src/setup.mk
A lot of developer confusion occurs when a project that was downloaded a while ago needs to be installed again, the user gets hit with a whole bunch of strange and frustrating conflicts. Bower does some silly stuff with looking at the `bower_components` directory before trying to build its tree that can be completely avoided if the `bower_components` directory isn't there.
let's do this bit for them
> Remove bower_components directory before install

- dotfiles/.pa11yci.js
Code added by Google Tag Manager may make some `pa11y` tests fail. This additional rule will exclude one source of errors.
More details on what led to this can be found [here](https://github.com/Financial-Times/next-subscribe/pull/746) and [here](https://financialtimes.slack.com/archives/C067V11G8/p1568712586010300).
> Exclude doubleclick iframes from Pa11y tests

- src/tasks/deploy.mk
This is following a [discussion on Slack](https://financialtimes.slack.com/archives/C08PF33EC/p1565272552028900).
We're in a situation on Conversion where we need to have E2E tests run on a predictable url and to block code from going out if tests fail. The best place to do this would be on staging, and to do that we need to break up the deploy task so that we can run our tests in between staging being set up and it being promoted to prod and then scaled down.
🐿 v2.10.0
> Split the deploy task into two sub-tasks for staging and promotion to prod.

- src/tasks/deploy.mk
Refactors the deploy assets command in n-gage to remove the dependency on n-heroku-tools for apps which are using Page Kit
[PR to add the aws-cli helpers](https://github.com/Financial-Times/next-ci-shared-helpers/pull/22)
[PR to add the upload assets to S3 helper](https://github.com/Financial-Times/next-ci-shared-helpers/pull/23)
Related issue on Page Kit: https://github.com/Financial-Times/next-ci-shared-helpers/issues/21
> replaces the existing nht deploy command with shared helpers 🐿 v2.12.5

- src/tasks/deploy.mk
Reverts Financial-Times/n-gage#213
This change introduced errors related to loading hashed assets which are discussed in this [ops-cops trello ticket](https://trello.com/c/5oMTap8b/1383-403s-on-next-search-page-related-to-hashed-assets)
This implementation assumed that the asset-upload step was triggered by CI, but it's not - the `make upload-assets` script is triggered as part of the `heroku-postbuild` script. 
We will need to rethink our implementation.
> Revert "replaces the existing nht deploy command with shared helpers 🐿 v2.12.5"

- dotfiles/.eslintrc.js
Ensures any usage of `.only` in test files located in the root level `/cypress` directory also has ES Lint check for `no-only-tests` applied.
This seems a lot simpler than overriding the Cypress default (i.e. keeping `/cypress` directory at root level, done in `next-retention`, `next-subscribe`, `next-profile`, and maybe more) by nesting the `/cypress` directory inside the root level `/test` directory.
This change will ensure that instances such as [this](https://github.com/Financial-Times/next-retention/pull/363/files) are caught in future.
> Include Cypress files in no-only-tests ES Lint check

- src/tasks/deploy.mk
**24 Jan 2019:**
This line makes smoke tests against the _staging_ app use **http**:
https://github.com/Financial-Times/n-gage/blob/master/src/tasks/deploy.mk#L90
It was switched from **https** to **http** in commit: `http for staging as well` https://github.com/Financial-Times/n-gage/pull/146/commits/3217f54ea5d056301ab4562f0f2804fcff3e21b9 (part of this PR: https://github.com/Financial-Times/n-gage/pull/146).
**04 Jul 2019:**
This line makes smoke tests against the _review_ apps use **https**:
https://github.com/Financial-Times/n-gage/blob/master/src/tasks/review-app.mk#L37
It was switched from **http** to **https** in PR: `use https for TEST_URL` https://github.com/Financial-Times/n-gage/pull/200.
---
On [`next-houston`](https://github.com/Financial-Times/next-houston), upon …
> Update http -> https for canary + staging apps

- package.json
- scripts/githooks.js
Todo (see also below):
Integration tests are failing due to [`src/setup.mk` lines 23-27](https://github.com/Financial-Times/n-gage/blob/c66177e63e496e7b425b6b5715460d4ef3ddd858/src/setup.mk#L23_L27) which checks that `n-gage` didn't modify existing hooks - with this PR, the old format is migrated automatically, so components using `n-gage` will need to be updated.
This would have to be done either after this PR is merged, or using `--no-verify` for those repositories which need changing, as otherwise `n-gage` will try to revert to the old format.
Also they don't seem to be working properly on CircleCI since they are passing 🤔 
Fixes #220
> Use new config format for Husky commit hooks

- README.md
- src/setup.mk
In most cases it's sensible for `n-gage` to automatically configure the git hooks that are run by Husky, however sometimes this behaviour isn't desirable e.g. if you have `n-gage` configured in a monorepo, where the git hooks are needed at the root of the project, but not in the directory for a package where `n-gage` is used to take care of things like installing dependencies and generating an `.env` file.
Example of using the new `DISABLE_GITHOOKS` flag: https://github.com/Financial-Times/globetrotter/pull/374/files#diff-d51759f948926f1349d4ea853fd7e010R1
> Add flag for disabling configuration of git hooks

- src/setup.mk
Previously this was causing issues for people with spaces in their `PATH` directories
See also #224
> Quote PATH variable to prevent space splitting

- .circleci/config.yml
renovate PRs for common dependencies often fill up our circleci queue. a paused job waiting for approval doesn't count towards concurrent jobs, and it's straightforward to start this build if we need to test the PR on CI.
because this branch name uses the same format as renovate, it should match the rule so we can test this.
> wait for approval before starting renovate PR builds

- secret-squirrel.js
- src/tasks/deploy.mk
deploy-hashed-assets is deprecated so we want to remove it from everything, this depends on applications removing their use of the asset-hashes.json file which should be done before upgrading to this version.
This is a breaking change.
Migration documentation for release notes:
Remove deploy-hashed-assets step in deploy which looks for a asset-hashes.json file in the project.
Check if you have a `asset-hashes.json` file, if you do not, there is nothing to do.
If you do have a `asset-hashes.json` file, migrate to using `public/manifest.json` which is generated by Page Kit by default.
> Remove deploy hashed assets deploy step

- dotfiles/.eslintrc.js
This fixes the warning which is currently emitted when ESLint is run on projects which are using React.
> Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
> Fix warning from eslint-plugin-react about version

- src/tasks/deploy.mk
diff best viewed [with whitespace ignored](https://github.com/Financial-Times/n-gage/pull/233/files?diff=split&w=1).
the deploy-assets task runs on heroku from the postbuild script. heroku sets NODE_ENV to "production" on production apps and "branch" on review apps.
"but kara there's so much repetition here why don't you refactor it" honey it took me nearly an hour to write this if statement correctly. i'm just not going there.
> deploy to preview bucket on branch apps

- src/tasks/env.mk
[CPP-299](https://financialtimes.atlassian.net/browse/CPP-299)
`make .env` logs you in if you are not logged in and if the VAULT_AUTH_GITHUB_TOKEN is set
I don't think there are any security implications for this since you need to have the VAULT_AUTH_GITHUB_TOKEN correctly set in your machine
> CPP-299 - Improve n-gage Vault UX

- secret-squirrel.js
- src/setup.mk
- src/tasks/install.mk
- keep current behaviour if package-lock.json is in gitignore
- if not, don't prune before install, and allow it to be created
- remove .metadata_never_index file creation, it [doesn't actually work](https://apple.stackexchange.com/questions/381646/does-metadata-never-index-work-for-keeping-folders-out-of-spotlight-in-catalina) question mark
- drive by cleaning up of unused functions
since the automated tests are only rudimentary "does `make install build` not crash" tests, linking this to a local repo and testing it in a number of scenarios would be appreciated (i've done this myself with `next-article`). instructions:
1. in the repo you're testing, delete `node_modules` and run `npm install ../n-gage` (assuming `n-gage` is in the same parent directory). this will link your local …
> Package lock

- src/tasks/install.mk
Jira card: [CPP-372 make install should use `npm ci` on CI/Heroku if package-lock.json exists](https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1051&modal=detail&selectedIssue=CPP-372)
Does it show that I have not written many Make or Shell scripts…? 😬 
I've try to intuit what is going on in this install task and other tasks to see what I can use to fulfil the brief and this is what I have come up with, though it's very easily possible that I have misinterpreted the function of some of those commands I've borrowed.
- [Tutorialspoint: Unix / Linux Shell - The if...elif...fi statement](https://www.tutorialspoint.com/unix/if-elif-statement.htm)
- [Linux.org: What does -z flag mean in shell script used in if condition](https://www.linux.org/threads/what-does-z-flag-mean-in …
> Revise install task to use 'npm ci' command

- package.json
Jira card: [CPP-397](https://financialtimes.atlassian.net/secure/RapidBoard.jspa?rapidView=1051&modal=detail&selectedIssue=CPP-397&search=n-gage) "n-gage - Address prototype pollution vulnerability"
> Upgrade yargs ^10.0.3 -> ^16.0.0 to fix Prototype Pollution

- src/tasks/deploy.mk
- src/tasks/review-app.mk
to support colleagues migrating their branches to MAIN
This should pull the code from whichever branch has been set as the default on Github, likely to be `main` or, pre-migration, `master.
> push to HEAD branch

- .circleci/config.yml
- .github/settings.yml
[Ticket CPP-442 Upgrade GitHub repos from `master` to `main`](https://financialtimes.atlassian.net/browse/CPP-442)<br/><br/>As an organisation we are moving away from the usage of `master` as a central branch and switching it to `main`, this is to avoid using unnecessary language that can be offensive. This PR is for making those changes. <br/><br/>This PR was created using a nori script<br/><br/>_Nori is a command-line application for managing changes across multiple (usually Github) repositories._
> CPP-442 Upgrade GitHub repos from master to main

- src/setup.mk
I found this bug after I started making some commits last week and after a while realised that the `pre-commit` hook defined in the project didn't seem to be running as running `make verify` was failing but I was still able to make commits. It turned out that the githook _was_ running fine but when committing from my git client ([magit](https://magit.vc)) it would not print the `eslint` errors I was seeing when running `make verify` in the terminal...
Previously, if you were using the `GLOB` function in a githook and had passed `--literal-pathspecs` to the `git` command that was hooked (as magit does [by default](https://magit.vc/manual/magit/My-Git-hooks-work-on-the-command_002dline-but-not-inside-Magit.html) for all `git` commands,) Git would automatically set `GIT_LITERAL_PATHSPECS` to …
> Force globs to respect Git wildcard characters

- .circleci/config.yml
The npm binary isn't persisted between jobs in a workflow but we don't usually need npm in the test job so it's not an issue. We do for n-gage however, as we're running npm installs in the integration tests.
> Install npm 7 in test step in CI
